name: Deploy Lambda to Production
on:
  push:
    branches:
      - main
env:
  DOCKER_IMAGE_NAME: fashion-clip:lambda
  DOCKERFILE_PATH: ./Dockerfile.aws.lambda
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push Docker Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.DOCKER_IMAGE_NAME }} ${{ env.DOCKER_IMAGE_NAME }} . -f ${{ env.DOCKERFILE_PATH }}
          docker push $ECR_REGISTRY/${{ env.DOCKER_IMAGE_NAME }}
      - name: Deploy Lambda
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: aws lambda update-function-code --function-name fashion-clip --image-uri $ECR_REGISTRY/${{ env.DOCKER_IMAGE_NAME }}